# Generated by Django 2.1.7 on 2019-03-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullaniciAdi', models.CharField(max_length=120, verbose_name='Kullanıcı Adı')),
                ('Parola', models.CharField(max_length=64, verbose_name='Parola')),
                ('isim', models.CharField(max_length=120)),
                ('soyisim', models.CharField(max_length=120)),
                ('eMail', models.EmailField(max_length=254)),
            ],
        ),
    ]
